//! Real tokenizer service for accurate token counting across providers.
//!
//! - OpenAI: tiktoken-rs (exact BPE via o200k_base / cl100k_base)
//! - Anthropic: Greedy longest-match over recovered Claude vocabulary (~96% accuracy)
//! - Google/fallback: Calibrated heuristic (chars / ratio, tuned per content type)

use once_cell::sync::Lazy;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Trie for greedy longest-match tokenization (Anthropic / ctoc approach)
// ---------------------------------------------------------------------------

struct TrieNode {
    children: HashMap<u8, Box<TrieNode>>,
    is_terminal: bool,
}

impl TrieNode {
    fn new() -> Self {
        Self {
            children: HashMap::new(),
            is_terminal: false,
        }
    }
}

struct Trie {
    root: TrieNode,
}

impl Trie {
    fn new() -> Self {
        Self {
            root: TrieNode::new(),
        }
    }

    fn insert(&mut self, token: &[u8]) {
        let mut node = &mut self.root;
        for &byte in token {
            node = node.children.entry(byte).or_insert_with(|| Box::new(TrieNode::new()));
        }
        node.is_terminal = true;
    }

    fn longest_match(&self, data: &[u8], pos: usize) -> usize {
        let mut node = &self.root;
        let mut best = 0;
        for i in pos..data.len() {
            match node.children.get(&data[i]) {
                Some(child) => {
                    node = child;
                    if node.is_terminal {
                        best = i - pos + 1;
                    }
                }
                None => break,
            }
        }
        best
    }

    fn count_tokens(&self, text: &str) -> u32 {
        let data = text.as_bytes();
        let mut count: u32 = 0;
        let mut pos = 0;
        while pos < data.len() {
            let match_len = self.longest_match(data, pos);
            if match_len == 0 {
                pos += 1; // unknown byte = 1 token (single-byte fallback)
            } else {
                pos += match_len;
            }
            count += 1;
        }
        count
    }
}

// ---------------------------------------------------------------------------
// Vocabulary loading (Anthropic)
// ---------------------------------------------------------------------------

/// Embedded Claude vocabulary generated by scripts/gen_claude_vocab.py.
/// Contains ~36K verified tokens as newline-delimited escaped strings.
/// Falls back to heuristic if vocab file is missing (first build before generation).
static CLAUDE_VOCAB_BYTES: &[u8] = include_bytes!("../data/claude_vocab.bin");

fn build_claude_trie() -> Trie {
    let mut trie = Trie::new();
    if CLAUDE_VOCAB_BYTES.is_empty() {
        eprintln!("[tokenizer] Claude vocab empty — Anthropic will use calibrated heuristic");
        return trie;
    }

    // Binary format: each token is length-prefixed (u16 LE) followed by raw bytes
    let data = CLAUDE_VOCAB_BYTES;
    let mut pos = 0;
    let mut count = 0u32;
    while pos + 2 <= data.len() {
        let len = u16::from_le_bytes([data[pos], data[pos + 1]]) as usize;
        pos += 2;
        if pos + len > data.len() {
            break;
        }
        trie.insert(&data[pos..pos + len]);
        pos += len;
        count += 1;
    }
    eprintln!("[tokenizer] Loaded {} Claude vocabulary tokens", count);
    trie
}

static CLAUDE_TRIE: Lazy<Trie> = Lazy::new(build_claude_trie);

// ---------------------------------------------------------------------------
// OpenAI tokenizer (tiktoken-rs)
// ---------------------------------------------------------------------------

fn count_openai_tokens(model: &str, content: &str) -> u32 {
    // Try model-specific BPE first, fall back to o200k_base
    let bpe = tiktoken_rs::get_bpe_from_model(model)
        .or_else(|_| tiktoken_rs::o200k_base())
        .unwrap_or_else(|_| tiktoken_rs::cl100k_base().expect("cl100k_base must be available"));

    bpe.encode_with_special_tokens(content).len() as u32
}

// ---------------------------------------------------------------------------
// Calibrated heuristic (Gemini / fallback)
// ---------------------------------------------------------------------------

fn count_heuristic_tokens(content: &str) -> u32 {
    if content.is_empty() {
        return 0;
    }
    let bytes = content.as_bytes();
    let len = bytes.len();

    let mut has_code = false;
    let mut newline_count = 0usize;
    let mut ws_count = 0usize;

    for &b in bytes {
        if b == b'\n' {
            newline_count += 1;
        }
        if b == b' ' || b == b'\t' || b == b'\n' || b == b'\r' {
            ws_count += 1;
        }
        if !has_code
            && (b == b'{' || b == b'}' || b == b'[' || b == b']'
                || b == b'(' || b == b')' || b == b';')
        {
            has_code = true;
        }
    }

    let line_count = newline_count + 1;
    let chars_per_line = len as f64 / line_count as f64;
    let ws_ratio = ws_count as f64 / len as f64;

    // Calibrated ratios (tuned against Gemini countTokens API on representative ATLS content)
    let chars_per_token = if has_code && chars_per_line > 200.0 {
        2.8 // minified
    } else if has_code && ws_ratio < 0.15 {
        3.2 // dense code
    } else if has_code {
        3.6 // normal code
    } else if ws_ratio > 0.45 {
        4.8 // whitespace-heavy
    } else if ws_ratio > 0.30 {
        4.2 // prose-ish
    } else {
        3.8 // mixed
    };

    ((len as f64) / chars_per_token).ceil() as u32
}

// ---------------------------------------------------------------------------
// Provider dispatch
// ---------------------------------------------------------------------------

/// Resolve which counting strategy to use for a given provider.
enum TokenizerKind {
    OpenAI,
    Anthropic,
    Heuristic,
}

fn resolve_kind(provider: &str) -> TokenizerKind {
    match provider {
        "openai" | "lmstudio" => TokenizerKind::OpenAI,
        "anthropic" => {
            if CLAUDE_VOCAB_BYTES.is_empty() {
                TokenizerKind::Heuristic
            } else {
                TokenizerKind::Anthropic
            }
        }
        _ => TokenizerKind::Heuristic, // google, unknown
    }
}

pub fn count_tokens_inner(provider: &str, model: &str, content: &str) -> u32 {
    if content.is_empty() {
        return 0;
    }
    match resolve_kind(provider) {
        TokenizerKind::OpenAI => count_openai_tokens(model, content),
        TokenizerKind::Anthropic => CLAUDE_TRIE.count_tokens(content),
        TokenizerKind::Heuristic => count_heuristic_tokens(content),
    }
}

pub fn count_tokens_batch_inner(
    provider: &str,
    model: &str,
    contents: &[String],
) -> Vec<u32> {
    contents.iter().map(|c| count_tokens_inner(provider, model, c)).collect()
}

// ---------------------------------------------------------------------------
// Provider-aware tool definition token counting
// ---------------------------------------------------------------------------

/// Count tokens for the serialized tool definitions, using real tokenizer.
pub fn count_tool_def_tokens_inner(provider: &str, model: &str) -> u32 {
    let tools = crate::ai_streaming::get_atls_tools(provider);
    let s = tools.to_string();
    count_tokens_inner(provider, model, &s)
}

// ---------------------------------------------------------------------------
// Tauri commands
// ---------------------------------------------------------------------------

/// Count tokens for a single string using the provider-appropriate tokenizer.
#[tauri::command]
pub fn count_tokens(provider: String, model: String, content: String) -> u32 {
    count_tokens_inner(&provider, &model, &content)
}

/// Count tokens for multiple strings in a single IPC call.
#[tauri::command]
pub fn count_tokens_batch(
    provider: String,
    model: String,
    contents: Vec<String>,
) -> Vec<u32> {
    count_tokens_batch_inner(&provider, &model, &contents)
}

/// Count tokens for tool definitions using real tokenizer (replaces len/3.5 heuristic).
#[tauri::command]
pub fn count_tool_def_tokens(provider: String, model: String) -> u32 {
    count_tool_def_tokens_inner(&provider, &model)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_trie_basic() {
        let mut trie = Trie::new();
        trie.insert(b"hello");
        trie.insert(b"he");
        trie.insert(b"world");

        // "hello" should match as one token (greedy longest)
        assert_eq!(trie.count_tokens("hello"), 1);
        // "helloworld" = "hello" + "world" = 2 tokens
        assert_eq!(trie.count_tokens("helloworld"), 2);
        // "hex" = "he" + "x"(fallback) = 2 tokens
        assert_eq!(trie.count_tokens("hex"), 2);
    }

    #[test]
    fn test_heuristic_basic() {
        let code = "function hello() { return 42; }";
        let tokens = count_heuristic_tokens(code);
        assert!(tokens > 0);
        assert!(tokens < 20);

        let empty = count_heuristic_tokens("");
        assert_eq!(empty, 0);
    }

    #[test]
    fn test_openai_basic() {
        let tokens = count_openai_tokens("gpt-4o", "Hello, world!");
        assert!(tokens > 0 && tokens < 10);
    }

    #[test]
    fn test_count_tokens_dispatch() {
        let text = "function test() { return true; }";

        let openai = count_tokens_inner("openai", "gpt-4o", text);
        let heuristic = count_tokens_inner("google", "gemini-2.5-pro", text);

        assert!(openai > 0);
        assert!(heuristic > 0);
        assert!(openai < 20);
        assert!(heuristic < 20);
    }

    #[test]
    fn test_claude_trie_loaded() {
        // Verify the Claude vocabulary was loaded (should have ~36K+ tokens)
        let text = "Hello, world! This is a test of the Claude tokenizer.";
        let tokens = CLAUDE_TRIE.count_tokens(text);
        assert!(tokens > 0);
        // With a real vocab, this should be much fewer tokens than bytes
        assert!(tokens < text.len() as u32, "Trie should compress text: {} tokens for {} bytes", tokens, text.len());
    }

    #[test]
    fn test_anthropic_dispatch() {
        let text = "export async function fetchData(url: string): Promise<Response> {\n  const resp = await fetch(url);\n  return resp;\n}";
        let anthropic = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", text);
        let openai = count_tokens_inner("openai", "gpt-4o", text);
        assert!(anthropic > 5 && anthropic < 60, "anthropic={}", anthropic);
        assert!(openai > 5 && openai < 60, "openai={}", openai);
    }

    /// Profile representative ATLS dynamic block format sections.
    /// This test prints token counts for each format variant so we can
    /// identify where tokenizer waste is highest.
    #[test]
    fn profile_dynamic_block_formats() {
        let providers = [("anthropic", "claude-sonnet-4-20250514"), ("openai", "gpt-4o")];

        let samples: Vec<(&str, &str)> = vec![
            // Stats line
            ("stats_line",
             "<<CTX 15k/200k (7%) | chunks:12 | pinned:3 | bb:1.2k | freed:0.5k | history:8k (chat:2.1k results:4.3k refs:1.6k) | cache:85% | staged:3.2k | batch:2.4ops/call | active:5(3.2k) stale:3(1.8k) dormant:4(0.6k)>>"),
            // Stats line — alternative with ASCII brackets
            ("stats_line_ascii",
             "[CTX 15k/200k (7%) | chunks:12 | pinned:3 | bb:1.2k | freed:0.5k | history:8k (chat:2.1k results:4.3k refs:1.6k) | cache:85% | staged:3.2k | batch:2.4ops/call | active:5(3.2k) stale:3(1.8k) dormant:4(0.6k)]"),
            // Chunk tag with guillemets
            ("chunk_tag_guillemet",
             "\u{00AB}h:a3bf12 tk:450 smart:src/services/aiService.ts\u{00BB}"),
            // Chunk tag with ASCII brackets
            ("chunk_tag_ascii",
             "[h:a3bf12 tk:450 smart:src/services/aiService.ts]"),
            // Hash ref in digest
            ("hash_ref_digest",
             "[-> h:abc123, 1500tk | read_file:src/services/aiService.ts]"),
            // Hash ref — tighter format
            ("hash_ref_tight",
             "[h:abc123 1500tk read_file:src/services/aiService.ts]"),
            // TOON workspace context
            ("toon_workspace",
             "Ctx:{file:\"src/services/aiService.ts\",line:42,branch:main,deps:[express,pg,zustand],lang:typescript}"),
            // JSON workspace context (for comparison)
            ("json_workspace",
             "Ctx:{\"file\":\"src/services/aiService.ts\",\"line\":42,\"branch\":\"main\",\"deps\":[\"express\",\"pg\",\"zustand\"],\"lang\":\"typescript\"}"),
            // Task/plan line
            ("task_plan",
             "<<TASK: Implement real tokenizer integration>>\n<<PLAN: [2/5 done] Design tokenizer -> Build Rust backend(done) -> Frontend wrapper(done) -> Migrate callers(active) -> Validate>>"),
            // Task/plan — ASCII brackets
            ("task_plan_ascii",
             "[TASK: Implement real tokenizer integration]\n[PLAN: [2/5 done] Design tokenizer -> Build Rust backend(done) -> Frontend wrapper(done) -> Migrate callers(active) -> Validate]"),
            // Blackboard entry
            ("bb_entry",
             "plan:current: Goal:real tokenizer|Done:rust backend,frontend wrapper|Next:migrate callers,validate"),
            // WM section header
            ("wm_header",
             "## WORKING MEMORY"),
            // Active engrams header
            ("active_header",
             "## ACTIVE ENGRAMS (subtask: migrate-callers)"),
            // Turn marker
            ("turn_marker",
             "<!-- WM:turn:15 -->"),
            // Hex hash (6 chars) — the pointer overhead
            ("hex_hash_6",
             "h:a3bf12"),
            // Hex hash (16 chars)
            ("hex_hash_16",
             "h:a3bf12c4e5d6f7a8"),
            // Symbol digest line
            ("symbol_digest",
             "  fn authenticate:15-32 | cls AuthService:34-89 | fn validateToken:91-120 | iface UserSession:122-145"),
            // Staged block header
            ("staged_header",
             "## STAGED (cached @ 10% cost, 3.2k tokens)"),
            // Staged snippet header
            ("staged_snippet",
             "[a3bf12] src/services/aiService.ts:1-50 (450tk)"),
            // Dormant line
            ("dormant_line",
             "[D] h:a3bf12 smart:src/services/aiService.ts (450tk) fn:authenticate,validateToken"),
        ];

        eprintln!("\n=== ATLS Dynamic Block Format Token Profile ===\n");
        eprintln!("{:<25} {:>6} {:>6} {:>6} {:>8}", "Section", "chars", "claude", "openai", "ratio");
        eprintln!("{}", "-".repeat(60));

        for (name, content) in &samples {
            let chars = content.len();
            let mut counts: Vec<u32> = Vec::new();
            for (provider, model) in &providers {
                counts.push(count_tokens_inner(provider, model, content));
            }
            let ratio = chars as f64 / counts[0] as f64;
            eprintln!("{:<25} {:>6} {:>6} {:>6} {:>8.2}",
                name, chars, counts[0], counts[1], ratio);
        }
        eprintln!("\n=== End Profile ===\n");

        // Compare guillemets vs ASCII for stats line
        let guill_stats = count_tokens_inner("anthropic", "claude-sonnet-4-20250514",
            "<<CTX 15k/200k (7%)>>");
        let ascii_stats = count_tokens_inner("anthropic", "claude-sonnet-4-20250514",
            "[CTX 15k/200k (7%)]");
        eprintln!("Guillemet overhead: <<...>> = {} tokens, [...] = {} tokens (delta: {})",
            guill_stats, ascii_stats, guill_stats as i32 - ascii_stats as i32);

        let guill_pair = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", "<<>>");
        let ascii_pair = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", "[]");
        eprintln!("Bare delimiters: <<>> = {} tokens, [] = {} tokens",
            guill_pair, ascii_pair);

        // Test chunk tag alternatives
        let alternatives: Vec<(&str, &str)> = vec![
            ("current", "\u{00AB}h:a3bf12 tk:450 smart:src/services/aiService.ts\u{00BB}"),
            ("no_prefix", "\u{00AB}a3bf12 450tk smart:src/services/aiService.ts\u{00BB}"),
            ("hash4", "\u{00AB}h:a3bf smart:src/services/aiService.ts 450tk\u{00BB}"),
            ("spaced", "[h:a3bf12 450 smart src/services/aiService.ts]"),
        ];
        eprintln!("\n--- Chunk tag alternatives ---");
        for (name, content) in &alternatives {
            let claude = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", content);
            let openai = count_tokens_inner("openai", "gpt-4o", content);
            eprintln!("{:<12} {:>3}ch {:>3}cl {:>3}oa  {}", name, content.len(), claude, openai, content);
        }

        // Test ref line alternatives
        let ref_alts: Vec<(&str, &str)> = vec![
            ("current", "[-> h:abc123, 1500tk | read_file:src/services/aiService.ts]"),
            ("compact", "[h:abc123 1500tk read_file:src/services/aiService.ts]"),
            ("arrow_drop", "[h:abc123 1.5k read_file:src/services/aiService.ts]"),
        ];
        eprintln!("\n--- Ref line alternatives ---");
        for (name, content) in &ref_alts {
            let claude = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", content);
            let openai = count_tokens_inner("openai", "gpt-4o", content);
            eprintln!("{:<12} {:>3}ch {:>3}cl {:>3}oa  {}", name, content.len(), claude, openai, content);
        }
    }

    /// Calibration test: measure heuristic vs real tokenizer ratios for representative content.
    /// Used to determine threshold adjustment factors for promptMemory.ts constants.
    #[test]
    fn calibration_heuristic_vs_real() {
        let samples: Vec<(&str, &str)> = vec![
            ("typescript_code",
             "export async function streamChatViaTauri(\n  config: AIConfig,\n  conversationHistory: Array<{ role: string; content: unknown }>,\n  callbacks: StreamCallbacks,\n  dynamicContextInput?: DynamicContextInput,\n): Promise<void> {\n  const { provider, model, apiKey } = config;\n  const appState = useAppStore.getState();\n  let round = 0;\n  let priorTurnBoundary = 0;\n  const abortController = new AbortController();\n  const isSessionValid = () => !abortController.signal.aborted;\n}"),
            ("json_tool_result",
             r#"{"results":[{"file":"src/services/aiService.ts","line":42,"symbol":"streamChatViaTauri","kind":"function","context":"export async function streamChatViaTauri("},{"file":"src/services/chatMiddleware.ts","line":91,"symbol":"historyCompressionMiddleware","kind":"function","context":"export const historyCompressionMiddleware: BeforeRoundMiddleware = async (ctx) => {"}],"total":2}"#),
            ("compressed_refs",
             "[h:abc123 1500tk read_file:src/services/aiService.ts]\n[h:def456 800tk search.code:streamChat]\n[h:789abc 2200tk read_file:src/stores/contextStore.ts]"),
            ("working_memory",
             "## WORKING MEMORY\n\u{0394}: 2 new, 1 dematerialized\nBB: 3 active entries, 1.2k tk\n## ACTIVE ENGRAMS (subtask: migrate-callers)\n\u{00AB}h:a3bf12 450tk smart src/services/aiService.ts\u{00BB}\nfn streamChatViaTauri:15-120 | fn buildDynamicContextBlock:200-300"),
            ("system_prompt_fragment",
             "## Batch Tool (shell = builds/git/packages ONLY; h:XXXX = universal pointer)\nUse one native execution surface: batch({version:\"1.0\",steps:[...]}).\n\n### Operation Families\nread: context, shaped, lines\nsearch: code, symbol, usage, similar, issues, patterns, memory\nchange: edit, create, delete, refactor, rollback, split_module"),
            ("stats_plus_bb",
             "<<CTX 15k/200k (7%) | chunks:12 | pinned:3 | bb:1.2k>>\n## BLACKBOARD\nplan:current: Goal:real tokenizer|Done:rust backend,frontend wrapper|Next:migrate callers,validate\ndesign:decisions: Use tiktoken-rs for OpenAI, ctoc greedy for Claude, heuristic for Gemini"),
        ];

        eprintln!("\n=== Heuristic vs Real Token Count Calibration ===\n");
        eprintln!("{:<25} {:>6} {:>8} {:>8} {:>8} {:>8}", "Content Type", "chars", "heuristic", "claude", "openai", "h/c ratio");
        eprintln!("{}", "-".repeat(70));

        for (name, content) in &samples {
            let heuristic = count_heuristic_tokens(content);
            let claude = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", content);
            let openai = count_tokens_inner("openai", "gpt-4o", content);
            let ratio = heuristic as f64 / claude as f64;
            eprintln!("{:<25} {:>6} {:>8} {:>8} {:>8} {:>8.3}",
                name, content.len(), heuristic, claude, openai, ratio);
        }
        eprintln!("\nRatio > 1.0 = heuristic overcounts (conservative)");
        eprintln!("Ratio < 1.0 = heuristic undercounts (dangerous - may blow context)");
        eprintln!("\n=== End Calibration ===\n");
    }

    /// Golden test: verify tokenizer consistency for ATLS format primitives.
    /// These are regression anchors — if counts drift, format changes or vocab
    /// updates need investigation.
    #[test]
    fn golden_format_token_counts() {
        // Hash ref (new compact format)
        let compact_ref = "[h:abc123 1500tk read_file:src/services/aiService.ts]";
        let claude = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", compact_ref);
        let openai = count_tokens_inner("openai", "gpt-4o", compact_ref);
        assert!(claude >= 18 && claude <= 26, "claude compact_ref={} (expected 18-26)", claude);
        assert!(openai >= 14 && openai <= 22, "openai compact_ref={} (expected 14-22)", openai);

        // Chunk tag (new format)
        let chunk_tag = "\u{00AB}h:a3bf12 450tk smart src/services/aiService.ts\u{00BB}";
        let claude_tag = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", chunk_tag);
        assert!(claude_tag >= 16 && claude_tag <= 24, "claude chunk_tag={} (expected 16-24)", claude_tag);

        // Stats line
        let stats = "<<CTX 15k/200k (7%) | chunks:12 | pinned:3 | bb:1.2k>>";
        let claude_stats = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", stats);
        assert!(claude_stats >= 20 && claude_stats <= 40, "claude stats={} (expected 20-40)", claude_stats);

        // OpenAI and Anthropic should agree within 30% for natural content
        let natural = "This is a test of the emergency broadcast system. If this had been an actual emergency.";
        let c_nat = count_tokens_inner("anthropic", "claude-sonnet-4-20250514", natural);
        let o_nat = count_tokens_inner("openai", "gpt-4o", natural);
        let diff_pct = ((c_nat as f64 - o_nat as f64) / o_nat as f64).abs();
        assert!(diff_pct < 0.30, "providers diverge too much on natural text: claude={} openai={} diff={}%",
            c_nat, o_nat, (diff_pct * 100.0) as u32);
    }
}
