/**
 * Reads Vitest coverage-summary.json and cargo-llvm-cov --json --summary-only exports,
 * and writes sorted lists of files with 0% line coverage (excluding configured paths).
 *
 * Usage (from atls-studio/):
 *   npx tsx scripts/list-coverage-gaps.ts [--fail-on-gaps]
 *
 * --fail-on-gaps  Exit with code 1 if any TS file has 0% line coverage (after exclusions).
 *
 * Env:
 *   ATLS_REPO_ROOT — repo root (default: parent of atls-studio/ directory)
 *
 * CI generates Rust summaries in `.github/workflows/ci.yml`:
 *   - Tauri: `atls-studio/src-tauri` → `cargo llvm-cov --all-features --lcov ...`
 *   - atls-rs: `cargo llvm-cov --workspace --all-features --lcov ...` then
 *     `cargo llvm-cov report --workspace --json --summary-only --output-path target/llvm-cov-atls-rs-summary.json`
 *
 * Local atls-rs JSON (for rust-atls-rs-zero-line-coverage.txt):
 *   cd ../atls-rs && cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info && \
 *     cargo llvm-cov report --workspace --json --summary-only --output-path target/llvm-cov-atls-rs-summary.json
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

type Exclusions = {
  ts?: { paths?: string[]; pathPrefixes?: string[]; notes?: string[] };
  rustTauri?: { paths?: string[]; notes?: string[] };
  rustAtlsRs?: { paths?: string[]; notes?: string[] };
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const ATLS_APP = dirname(__dirname);
const repoRoot = process.env.ATLS_REPO_ROOT ?? dirname(ATLS_APP);

function normPath(p: string): string {
  return p.replace(/\\/g, "/").replace(/\/+$/, "");
}

function repoRel(absPath: string): string {
  return normPath(relative(repoRoot, absPath));
}

function normalizeForMatch(repoRelPath: string): string {
  return normPath(repoRelPath).toLowerCase();
}

function tsExcluded(rel: string, ex: Exclusions): boolean {
  const n = normalizeForMatch(rel);
  for (const p of ex.ts?.paths ?? []) {
    if (normalizeForMatch(p) === n) return true;
  }
  for (const pre of ex.ts?.pathPrefixes ?? []) {
    if (n.startsWith(normalizeForMatch(pre))) return true;
  }
  return false;
}

function rustExcluded(rel: string, ex: Exclusions, kind: "tauri" | "atlsRs"): boolean {
  const key = kind === "tauri" ? "rustTauri" : "rustAtlsRs";
  const n = normalizeForMatch(rel);
  for (const p of ex[key]?.paths ?? []) {
    if (normalizeForMatch(p) === n) return true;
  }
  return false;
}

function loadExclusions(): Exclusions {
  const exPath = join(ATLS_APP, "coverage-gap-exclusions.json");
  if (!existsSync(exPath)) return {};
  return JSON.parse(readFileSync(exPath, "utf8")) as Exclusions;
}

function parseVitestZeroLines(summaryPath: string, ex: Exclusions): string[] {
  const raw = JSON.parse(readFileSync(summaryPath, "utf8")) as Record<
    string,
    { lines?: { total: number; pct: number } }
  >;
  const out: string[] = [];
  for (const [key, val] of Object.entries(raw)) {
    if (key === "total") continue;
    const lines = val.lines;
    if (!lines || lines.total <= 0 || lines.pct !== 0) continue;
    const rel = repoRel(key);
    if (!rel.startsWith("atls-studio/src/")) continue;
    if (tsExcluded(rel, ex)) continue;
    out.push(rel);
  }
  return out.sort();
}

type LlvmSummaryFile = {
  filename: string;
  summary: { lines: { count: number; covered: number; percent: number } };
};

function parseLlvmJsonZeroLines(jsonPath: string, prefix: string, ex: Exclusions, kind: "tauri" | "atlsRs"): string[] {
  const raw = JSON.parse(readFileSync(jsonPath, "utf8")) as {
    data: { files: LlvmSummaryFile[] }[];
  };
  const files = raw.data?.[0]?.files ?? [];
  const out: string[] = [];
  for (const f of files) {
    const { count, percent } = f.summary.lines;
    if (count <= 0 || percent !== 0) continue;
    const rel = repoRel(f.filename);
    if (!normPath(rel).startsWith(normPath(prefix))) continue;
    if (rustExcluded(rel, ex, kind)) continue;
    out.push(rel);
  }
  return out.sort();
}

function main(): void {
  const ex = loadExclusions();
  const outDir = join(ATLS_APP, "test-gap-reports");
  mkdirSync(outDir, { recursive: true });

  const vitestPath = join(ATLS_APP, "coverage", "coverage-summary.json");
  if (!existsSync(vitestPath)) {
    console.error(
      `Missing ${vitestPath}. Run: npm run test:coverage`,
    );
    process.exit(1);
  }

  const tsGaps = parseVitestZeroLines(vitestPath, ex);
  const tsBody = [
    "# TypeScript / React (Vitest) — 0% line coverage",
    "Generated by scripts/list-coverage-gaps.ts from coverage/coverage-summary.json",
    `Files: ${tsGaps.length}`,
    "",
    ...tsGaps,
    "",
  ].join("\n");
  writeFileSync(join(outDir, "ts-zero-line-coverage.txt"), tsBody, "utf8");

  const tauriJson = join(ATLS_APP, "src-tauri", "target", "llvm-cov-tauri-summary.json");
  if (existsSync(tauriJson)) {
    const rustTauri = parseLlvmJsonZeroLines(tauriJson, "atls-studio/src-tauri/src", ex, "tauri");
    writeFileSync(
      join(outDir, "rust-src-tauri-zero-line-coverage.txt"),
      [
        "# Rust (src-tauri) — 0% line coverage",
        "Generated from src-tauri/target/llvm-cov-tauri-summary.json (cargo llvm-cov --json --summary-only)",
        `Files: ${rustTauri.length}`,
        "",
        ...rustTauri,
        "",
      ].join("\n"),
      "utf8",
    );
  } else {
    writeFileSync(
      join(outDir, "rust-src-tauri-zero-line-coverage.txt"),
      [
        "# Rust (src-tauri) — not generated",
        "Run from repo root:",
        "  cd atls-studio/src-tauri && cargo llvm-cov --json --summary-only --output-path target/llvm-cov-tauri-summary.json",
        "",
      ].join("\n"),
      "utf8",
    );
  }

  const atlsRsJson = join(repoRoot, "atls-rs", "target", "llvm-cov-atls-rs-summary.json");
  if (existsSync(atlsRsJson)) {
    const rustRs = parseLlvmJsonZeroLines(atlsRsJson, "atls-rs/crates", ex, "atlsRs");
    writeFileSync(
      join(outDir, "rust-atls-rs-zero-line-coverage.txt"),
      [
        "# Rust (atls-rs) — 0% line coverage",
        "Generated from atls-rs/target/llvm-cov-atls-rs-summary.json (cargo llvm-cov --workspace --json --summary-only)",
        `Files: ${rustRs.length}`,
        "",
        ...rustRs,
        "",
      ].join("\n"),
      "utf8",
    );
  } else {
    writeFileSync(
      join(outDir, "rust-atls-rs-zero-line-coverage.txt"),
      [
        "# Rust (atls-rs) — not generated",
        "Run from repo root:",
        "  cd atls-rs && cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info && \\",
        "    cargo llvm-cov report --workspace --json --summary-only --output-path target/llvm-cov-atls-rs-summary.json",
        "",
      ].join("\n"),
      "utf8",
    );
  }

  writeFileSync(
    join(outDir, "scripts-out-of-scope.txt"),
    [
      "# Scripts not under Vitest src/ include",
      "These are intentionally out of scope for the Vitest coverage report (see coverage-gap-exclusions.json).",
      "",
      "atls-studio/scripts/fetch-models.ts",
      "",
    ].join("\n"),
    "utf8",
  );

  console.log(`Wrote gap reports under ${outDir}`);
  console.log(`  TS 0% files: ${tsGaps.length}`);

  const failOnGaps = process.argv.includes("--fail-on-gaps");
  if (failOnGaps && tsGaps.length > 0) {
    console.error(`--fail-on-gaps: ${tsGaps.length} TS file(s) still at 0% line coverage.`);
    process.exit(1);
  }
}

main();
